# Generated by Django 2.2 on 2020-05-16 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200516_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='header_image',
            field=models.ImageField(default='default.jpg', upload_to='images/'),
        ),
    ]
